### ISSUE TITLE
Twitter logo

### ISSUE THREAD

**Issue by DarrenN** [papers-we-love/san-diego#3]
Good morning!

We're working with local chapters to try and bring the use of the Papers We Love identity closer together. To that end we're working on a system for chapters that we started with Portland to provide each chapter with some custom graphics they can use for Twitter profiles and other applications. I've attached a set for San Diego. Happy to work with you if you'd like to change it up a little: for instance [Portland went with PDX](https://twitter.com/pwlpdx) instead of the city name proper and [New York rolls with NYC](https://twitter.com/paperswelovenyc). 

Thanks again and congrats on a successful chapter!

https://www.dropbox.com/s/6gcko7kp2v19b8c/pwl-san-diego.zip?dl=0

**Comment by DarrenN** [comment]
@chrishiestand please update the PWL twitter and meetup logos when you have a chance. Thanks!

- D

**Comment by chrishiestand** [comment]
These look great for now, thanks. This clears up a point of confusion and disagreement we local organizers had and so I imagine this is going to be a big aggregate time saver, thanks!

**Comment by chrishiestand** [comment]
@DarrenN For youtube (ie Google), the twitter friendly logo does not fit. Google recommends a 16:9 aspect ratio with 2560x1440 resolution.
https://support.google.com/youtube/answer/2972003?co=GENIE.Platform%3DDesktop&hl=en 

Might it be possible to get similar art in that size?

**Comment by DarrenN** [comment]
@chrishiestand good catch - I'll get something together for you this weekend.

**Comment by chrishiestand** [comment]
@DarrenN great thanks! And I'm sure you understood my meaning but I was unclear - I mean the "banner" image.

**Comment by DarrenN** [comment]
Looks like Meetup.com changed their image size as well, so I've attached an updated image for that and YouTube.

https://www.dropbox.com/s/s2wb377u0qooq0n/pwl-meetup-banner-sandiego.png?dl=0
https://www.dropbox.com/s/si5mh0ehk6ohhnq/pwl-youtube-banner-sandiego.png?dl=0

Let me know if those don't work out and thanks again!

**Comment by chrishiestand** [comment]
Thanks for the quick turn-around @DarrenN!

On the next step with Google there is an issue however - they way they crop the image for different devices adds further constraints:

![image](https://user-images.githubusercontent.com/100825/36084976-e7526398-0f76-11e8-87e2-5fb69b007e35.png)

So we might need to make the font smaller or replace the text with "PWLSD". I'm okay with either approach.

On this template image, Google says the text and logo "safe area" is 1546x423:
![channel art template fireworks](https://user-images.githubusercontent.com/100825/36085033-8554920a-0f77-11e8-8b77-bbd31bacd869.png)

**Comment by chrishiestand** [comment]
PS The meetup logo looks and fits great!

**Comment by DarrenN** [comment]
Allrighty lets try this one -> https://www.dropbox.com/s/si5mh0ehk6ohhnq/pwl-youtube-banner-sandiego.png?dl=0

Thanks for taking the time to work this out, appreciate it!

**Comment by chrishiestand** [comment]
Perfecto! It's looking good: https://www.youtube.com/channel/UCYPNnoVAQqb2Mue9v9f2euA

Thanks for all your hard work @DarrenN!
